name: thesis_ippp
channels:
  - conda-forge
  - fastai
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _py-xgboost-mutex=2.0=cpu_2
  - _python_abi3_support=1.0=hd8ed1ab_2
  - annotated-doc=0.0.4=pyhcf101f3_0
  - anyio=4.12.1=pyhcf101f3_0
  - aom=3.12.1=h00a0c3c_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - autograd=1.8.0=py312haa95532_1
  - autograd-gamma=0.5.0=py312haa95532_1
  - backports.zstd=1.3.0=py312h06d0912_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312h540bb41_1
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.2.25=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2026.2.25=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h214f63a_0
  - cpython=3.12.12=py312hd8ed1ab_2
  - cuda-cudart=12.9.79=he0c23c2_0
  - cuda-cudart_win-64=12.9.79=he0c23c2_0
  - cuda-version=12.9=h4f385c5_3
  - cycler=0.12.1=py312haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.20=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - ecos=2.0.14=np2py312h226b611_3
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.4=hd7fb8db_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py312h02ab6af_0
  - formulaic=1.2.1=py312haa95532_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=hfbffc0b_0
  - fribidi=1.0.16=haf45083_0
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h3ef6528_1
  - hf-xet=1.2.1=py310hfb9af98_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=1.5.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=pyhd8ed1ab_0
  - imbalanced-learn=0.14.1=pyhd8ed1ab_0
  - intel-openmp=2025.0.0=haa95532_1164
  - interface_meta=1.3.0=py312haa95532_2
  - ipykernel=7.2.0=pyh6dadd2b_1
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py312h03f52e7_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.3.0=h5bd13ec_0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.86.3=h9bccc14_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc89ec93_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libosqp=1.0.0=np2py312h325a191_2
  - libpng=1.6.54=ha15c746_0
  - libqdldl=0.1.8=he0c23c2_1
  - libsodium=1.0.20=hc70643c_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxgboost=3.2.0=h585ebfc_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lifelines=0.30.1=pyhd8ed1ab_0
  - llvmlite=0.46.0=py312hdb9728c_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h05f76fc_0
  - matplotlib-base=3.10.8=py312h26e45b9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - narwhals=2.7.0=py312haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numba=0.63.1=py312h560f1c9_0
  - numexpr=2.14.1=py312h7660c64_0
  - numpy=2.3.5=py312h050da96_0
  - numpy-base=2.3.5=py312h1e017a8_0
  - openssl=3.6.1=hf411b9b_1
  - osqp=1.1.1=np2py312ha76dc74_0
  - packaging=25.0=py312haa95532_1
  - parso=0.8.6=pyhcf101f3_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.1.0=py312h6b7a805_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.9.2=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py312he5662c2_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.2.0=py312haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=py312haa95532_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.12=3_cp312
  - pytz=2025.2=py312haa95532_0
  - pywin32=311=py312h829343e_1
  - pyyaml=6.0.3=py312h05f76fc_1
  - pyzmq=27.1.0=py312h343a6d4_2
  - qdldl-python=0.1.7.post5=np2py312ha76dc74_3
  - regex=2026.2.19=py312he06e257_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.3.3=pyhcf101f3_0
  - safetensors=0.7.0=py312hb0142fd_0
  - scikit-learn=1.8.0=py312h7f7e138_0
  - scikit-survival=0.27.0=py312h78d62e6_0
  - scipy=1.17.0=py312h2074b4c_0
  - seaborn=0.13.2=py312haa95532_3
  - setuptools=80.10.2=py312haa95532_0
  - shap=0.50.0=cuda129_py312h6f1b920_201
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - sklearn-compat=0.1.5=pyhd8ed1ab_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - threadpoolctl=3.5.0=py312h4442805_1
  - tk=8.6.15=hf199647_0
  - tokenizers=0.22.2=py312h362b069_0
  - tornado=6.5.4=py312he06e257_0
  - tqdm=4.67.3=pyha7b4d00_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=5.2.0=pyhd8ed1ab_0
  - typer=0.24.0=pyhcf101f3_0
  - typer-slim=0.24.0=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - wheel=0.46.3=py312haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=2.0.1=py312h02ab6af_0
  - xgboost=3.2.0=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - et-xmlfile==2.0.0
      - filelock==3.20.0
      - fsspec==2025.12.0
      - mpmath==1.3.0
      - networkx==3.6.1
      - openpyxl==3.1.5
      - pandas==3.0.1
      - sympy==1.14.0
      - torch==2.10.0+cu126
      - torchvision==0.25.0+cu126
prefix: C:\Users\rjbel\anaconda3\envs\thesis_ippp
